services:
  - type: web
    name: smart-complaint-management
    env: static
    rootDir: frontend/smart-complaint-management
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html